const cfg=window.APP_CONFIG||{},configured=cfg.SUPABASE_URL?.startsWith('https://')&&!cfg.SUPABASE_URL.includes('ВСТАВЬТЕ')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes('ВСТАВЬТЕ');
const db=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null,$=id=>document.getElementById(id),rub=new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}),fmt=new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',year:'numeric'});let items=[],shown=[],editId=null;
const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,plus=n=>{const d=new Date();d.setDate(d.getDate()+n);return dateKey(d)},sum=a=>a.reduce((s,x)=>s+Number(x.amount),0),safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function message(text,bad=false){$('message').innerHTML=text?`<div class="${bad?'error':'notice'}">${bad?'':'✓ '}${safe(text)}</div>`:'';if(text&&!bad)setTimeout(()=>message(''),3500)}
function connection(text,state){$('connectionText').textContent=text;$('connectionText').parentElement.className=`connection ${state||''}`}
async function load(){if(!db){connection('Нужно подключить Supabase','bad');message('Откройте config.js и вставьте Project URL и anon public key из Supabase.',true);render();return}connection('Загружаем общую базу…');const {data,error}=await db.from('payments').select('*').order('due_date').order('id');if(error){connection('Ошибка подключения','bad');message(error.message,true);return}items=data||[];connection('Общая база подключена','ok');fillSuppliers();render()}
function fillSuppliers(){const current=$('supplier').value,names=[...new Set(items.map(x=>x.supplier))].sort((a,b)=>a.localeCompare(b,'ru'));$('supplier').innerHTML='<option value="">Все поставщики</option>'+names.map(x=>`<option ${x===current?'selected':''}>${safe(x)}</option>`).join('')}
function render(){const q=$('search').value.trim().toLowerCase(),s=$('supplier').value,m=$('methodFilter').value,from=$('from').value,to=$('to').value;shown=items.filter(x=>(!q||[x.supplier,x.purpose,x.method,x.document,x.note,x.amount].join(' ').toLowerCase().includes(q))&&(!s||x.supplier===s)&&(!m||x.method===m)&&(!from||x.due_date>=from)&&(!to||x.due_date<=to));const today=dateKey(),tomorrow=plus(1),week=plus(7),cards=[['Записи на сегодня',sum(items.filter(x=>x.due_date===today)),1],['Записи на завтра',sum(items.filter(x=>x.due_date===tomorrow))],['Ближайшие 7 дней',sum(items.filter(x=>x.due_date>=today&&x.due_date<=week))],['Всего в журнале',sum(items)]];$('cards').innerHTML=cards.map(([t,v,a])=>`<article class="card ${a?'accent':''}"><span>${t}</span><b>${rub.format(v)}</b></article>`).join('');$('counter').textContent=`Показано ${shown.length} из ${items.length}`;$('filteredSum').textContent=rub.format(sum(shown));$('rows').innerHTML=shown.length?shown.map(x=>`<tr><td><b>${fmt.format(new Date(x.due_date+'T12:00'))}</b></td><td><b>${safe(x.supplier)}</b><span>${safe(x.purpose||x.note||'Без назначения')}</span></td><td class="money">${rub.format(x.amount)}</td><td>${safe(x.method)}</td><td><div class="rowActions"><button onclick="editEntry(${x.id})">✎</button><button onclick="deleteEntry(${x.id})">×</button></div></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Записей не найдено</td></tr>'}
function openForm(x=null){editId=x?.id||null;$('formTitle').textContent=x?'Изменить запись':'Новая запись';$('date').value=x?.due_date||dateKey();$('amount').value=x?.amount||'';$('name').value=x?.supplier||'';$('purpose').value=x?.purpose||'';$('method').value=x?.method||'Перевод';$('document').value=x?.document||'';$('note').value=x?.note||'';$('modal').classList.remove('hidden');setTimeout(()=>$('name').focus(),50)}function closeForm(){$('modal').classList.add('hidden');editId=null}
window.editEntry=id=>openForm(items.find(x=>x.id===id));window.deleteEntry=async id=>{if(!db||!confirm('Удалить эту запись?'))return;const {error}=await db.from('payments').delete().eq('id',id);if(error)return message(error.message,true);await load();message('Запись удалена')};
$('entryForm').onsubmit=async e=>{e.preventDefault();if(!db)return message('Сначала подключите Supabase в config.js',true);const record={due_date:$('date').value,supplier:$('name').value.trim(),amount:Number($('amount').value),purpose:$('purpose').value.trim(),method:$('method').value,document:$('document').value.trim(),note:$('note').value.trim(),updated_at:new Date().toISOString()},query=editId?db.from('payments').update(record).eq('id',editId):db.from('payments').insert(record),{error}=await query;if(error)return message(error.message,true);closeForm();await load();message('Запись сохранена')};
$('addBtn').onclick=()=>openForm();$('closeBtn').onclick=$('cancelBtn').onclick=closeForm;$('modal').onclick=e=>{if(e.target===$('modal'))closeForm()};["search","supplier","methodFilter","from","to"].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('resetBtn').onclick=()=>{$('search').value='';$('supplier').value='';$('methodFilter').value='';$('from').value='';$('to').value='';render()};
document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{const t=b.dataset.range,today=dateKey(),tomorrow=plus(1);$('from').value='';$('to').value='';if(t==='today')$('from').value=$('to').value=today;if(t==='tomorrow')$('from').value=$('to').value=tomorrow;if(t==='week'){$('from').value=today;$('to').value=plus(7)}if(t==='future')$('from').value=today;if(t==='month'){const d=new Date();$('from').value=`${today.slice(0,8)}01`;$('to').value=dateKey(new Date(d.getFullYear(),d.getMonth()+1,0))}render()});
$('importBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{if(!db)return message('Сначала подключите Supabase',true);const file=e.target.files[0];if(!file)return;try{const wb=XLSX.read(await file.arrayBuffer(),{cellDates:true}),ws=wb.Sheets['Выплаты']||wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{header:1,raw:true,defval:''}),hi=rows.findIndex(r=>r.some(v=>['Дата','Дата выплаты'].includes(String(v).trim())));if(hi<0)throw Error('Не найдена строка заголовков');const h=rows[hi].map(v=>String(v).trim()),col=(...n)=>n.map(x=>h.indexOf(x)).find(i=>i>=0)??-1,dc=col('Дата','Дата выплаты'),sc=col('Поставщик'),ac=col('Сумма'),parse=v=>{if(v instanceof Date)return dateKey(v);const m=String(v).match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})$/);return m?`${m[3].length===2?'20'+m[3]:m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:''},records=rows.slice(hi+1).flatMap(r=>{const due_date=parse(r[dc]),supplier=String(r[sc]||'').trim(),amount=Number(r[ac]||0);return due_date&&supplier&&amount>0?[{due_date,supplier,amount,purpose:String(r[col('Назначение / товар')]||''),method:String(r[col('Способ оплаты')]||'Не указано'),document:String(r[col('Документ / чек')]||''),note:String(r[col('Примечание')]||'')}]:[]});const {error}=await db.from('payments').insert(records);if(error)throw error;await load();message(`Импортировано записей: ${records.length}`)}catch(err){message(`Ошибка импорта: ${err.message}`,true)}e.target.value=''};
$('exportBtn').onclick=()=>{const data=[['Дата','Поставщик','Сумма','Назначение / товар','Способ оплаты','Документ / чек','Примечание'],...shown.map(x=>[x.due_date,x.supplier,x.amount,x.purpose,x.method,x.document,x.note])],ws=XLSX.utils.aoa_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Выплаты');XLSX.writeFile(wb,`журнал-${dateKey()}.xlsx`)};load();
