create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  due_date date not null,
  supplier text not null,
  amount numeric(14,2) not null check (amount > 0),
  purpose text not null default '',
  method text not null default 'Перевод',
  document text not null default '',
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists payments_due_date_idx on public.payments(due_date);
alter table public.payments enable row level security;
drop policy if exists "public journal read" on public.payments;
drop policy if exists "public journal insert" on public.payments;
drop policy if exists "public journal update" on public.payments;
drop policy if exists "public journal delete" on public.payments;
create policy "public journal read" on public.payments for select to anon using (true);
create policy "public journal insert" on public.payments for insert to anon with check (true);
create policy "public journal update" on public.payments for update to anon using (true) with check (true);
create policy "public journal delete" on public.payments for delete to anon using (true);
